"use client";

import { type FormEvent, useEffect, useState } from "react";
import { z } from "zod";
import { httpClient } from "@/src/shared/api";
import { getRequestErrorMessage } from "@/src/shared/api/abp-error";
import { Button, Dialog, SelectField, StatusMessage, TextAreaField, TextField } from "@/src/shared/ui";
import { adminAuditJustificationSchema } from "./admin-action-validation";

export type EditableCustomerAccount = { email: string; firstName: string; id: number; isActive: boolean; lastName: string; membershipId: number | null; tenantId: number };
const schema = z.object({ email: z.string().trim().email("Enter a valid email address."), firstName: z.string().trim().min(1, "First name is required."), isActive: z.boolean(), justification: adminAuditJustificationSchema, lastName: z.string().trim().min(1, "Last name is required."), membershipId: z.union([z.literal(""), z.coerce.number().int().positive()]).transform((value) => value === "" ? null : value) });

export const EditCustomerAccountDialog = ({ customer, onUpdated }: { customer: EditableCustomerAccount; onUpdated: () => void | Promise<void> }) => {
  const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string>(); const [errors, setErrors] = useState<Record<string, string>>({});
  const [membershipOptions, setMembershipOptions] = useState<{ id: number; name: string }[]>([]);
  useEffect(() => { if (!open) return; void httpClient.get<{ id: number; name: string }[]>(`/api/services/app/AdminCustomer/GetMembershipOptions?TenantId=${customer.tenantId}`).then(setMembershipOptions).catch((requestError) => setError(getRequestErrorMessage(requestError, "Membership plans could not be loaded for this area."))); }, [customer.tenantId, open]);
  const close = () => { setOpen(false); setError(undefined); setErrors({}); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const parsed = schema.safeParse({ email: data.get("email"), firstName: data.get("firstName"), isActive: data.get("isActive") === "on", justification: data.get("justification"), lastName: data.get("lastName"), membershipId: data.get("membershipId") }); if (!parsed.success) { setErrors(Object.fromEntries(parsed.error.issues.map((issue) => [String(issue.path[0]), issue.message]))); return; } setSubmitting(true); setError(undefined); try { await httpClient.put("/api/services/app/AdminCustomer/Update", { id: customer.id, ...parsed.data }); await onUpdated(); close(); } catch (requestError) { setError(getRequestErrorMessage(requestError, "The customer account could not be updated. No changes were saved.")); } finally { setSubmitting(false); } };
  return <><Button onClick={() => setOpen(true)} size="sm" variant="outline">Edit account</Button><Dialog onClose={close} open={open} size="lg" title="Edit customer account"><form className="grid gap-4 sm:grid-cols-2" noValidate onSubmit={submit}><TextField defaultValue={customer.firstName} errorMessage={errors.firstName} label="First name" name="firstName" required /><TextField defaultValue={customer.lastName} errorMessage={errors.lastName} label="Last name" name="lastName" required /><TextField className="sm:col-span-2" defaultValue={customer.email} errorMessage={errors.email} label="Email address" name="email" required type="email" /><SelectField defaultValue={customer.membershipId ?? ""} errorMessage={errors.membershipId} label="Membership plan" name="membershipId"><option value="">Not yet enrolled</option>{membershipOptions.map((membership) => <option key={membership.id} value={membership.id}>{membership.name}</option>)}</SelectField><label className="flex items-center gap-2 text-sm font-medium"><input defaultChecked={customer.isActive} name="isActive" type="checkbox" /> Account is active</label><TextAreaField className="sm:col-span-2" errorMessage={errors.justification} label="Reason for change" maxLength={500} name="justification" required rows={3} />{error ? <StatusMessage className="sm:col-span-2" tone="error">{error}</StatusMessage> : null}<div className="flex justify-end gap-3 sm:col-span-2"><Button onClick={close} variant="ghost">Cancel</Button><Button isLoading={submitting} type="submit">Save changes</Button></div></form></Dialog></>;
};
